wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/examples/launch_train_widowx_cql.py
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.12
    start_time: 1685817370
    t:
      1:
      - 2
      - 3
      - 12
      - 45
      3:
      - 14
      - 16
      4: 3.8.12
      5: 0.12.11
      8:
      - 2
      - 5
actor_lr:
  desc: null
  value: 0.0001
adam_weight_decay:
  desc: null
  value: -1.0
add_prev_actions:
  desc: null
  value: false
add_states:
  desc: null
  value: 1
algorithm:
  desc: null
  value: cql_encodersep
alpha_schedule_interval:
  desc: null
  value: -1.0
alpha_schedule_ratio:
  desc: null
  value: 1.0
azure:
  desc: null
  value: false
backup_entropy:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 64
bound_q_with_mc:
  desc: null
  value: false
bridge_clip_traj_length:
  desc: null
  value: -1
checkpoint_interval:
  desc: null
  value: 5000
cnn_features:
  desc: null
  value:
  - 32
  - 32
  - 32
  - 32
cnn_padding:
  desc: null
  value: VALID
cnn_strides:
  desc: null
  value:
  - 2
  - 1
  - 1
  - 1
color_jitter:
  desc: null
  value: 1
config:
  desc: null
  value: examples/configs/offline_pixels_default_real.py
cql_alpha:
  desc: null
  value: 5.0
cql_alpha_offline_finetuning:
  desc: null
  value: -1.0
cql_alpha_online_finetuning:
  desc: null
  value: -1.0
critic_lr:
  desc: null
  value: 0.0003
critic_reduction:
  desc: null
  value: min
dataset:
  desc: null
  value: debug
decay_steps:
  desc: null
  value: null
discount:
  desc: null
  value: 0.96
dr3_coefficient:
  desc: null
  value: 0.0
dropout_rate:
  desc: null
  value: null
encoder_key:
  desc: null
  value: agent/value/params/encoder
encoder_norm:
  desc: null
  value: batch
encoder_resize_dim:
  desc: null
  value: 128
encoder_type:
  desc: null
  value: small
episode_timelimit:
  desc: null
  value: 40
eval_episodes:
  desc: null
  value: 2
eval_interval:
  desc: null
  value: 500
eval_only:
  desc: null
  value: false
frame_stack:
  desc: null
  value: 1
freeze_encoders_actor:
  desc: null
  value: false
freeze_encoders_critic:
  desc: null
  value: false
from_states:
  desc: null
  value: false
hidden_dims:
  desc: null
  value:
  - 256
  - 256
init_temperature:
  desc: null
  value: 1.0
keep_mc_bound_online:
  desc: null
  value: false
latent_dim:
  desc: null
  value: 50
launch_group_id:
  desc: null
  value: ''
log_interval:
  desc: null
  value: 1000
max_q_backup:
  desc: null
  value: 1
max_steps:
  desc: null
  value: 2000000
mc_penalty_coefficient:
  desc: null
  value: 0.0
method:
  desc: null
  value: 0
method_const:
  desc: null
  value: 0.0
method_type:
  desc: null
  value: 0
multi_grad_step:
  desc: null
  value: 5
multi_viewpoint:
  desc: null
  value: 1
num_bridge_traj:
  desc: null
  value: -1
num_demo:
  desc: null
  value: 5
num_final_reward_steps:
  desc: null
  value: 1
num_online_gradsteps_batch:
  desc: null
  value: -1
num_target_traj:
  desc: null
  value: -1
obs_latency:
  desc: null
  value: 0
offline_finetuning_start:
  desc: null
  value: -1
offline_only:
  desc: null
  value: 1
offline_only_restore_onlinedata:
  desc: null
  value: null
online_bound_nstep_return:
  desc: null
  value: -1
online_cql_alpha_sep_offline:
  desc: null
  value: -1.0
online_cql_alpha_sep_offline_bridge:
  desc: null
  value: -1.0
online_cql_alpha_sep_offline_target:
  desc: null
  value: -1.0
online_cql_alpha_sep_online:
  desc: null
  value: -1.0
online_from_scratch:
  desc: null
  value: false
online_mixing_ratio:
  desc: null
  value: 0.5
online_pos_neg_ratio:
  desc: null
  value: -1
online_start:
  desc: null
  value: 10000000000000
only_add_success:
  desc: null
  value: false
outputdir:
  desc: null
  value: /nfs/kun2/users/asap7772/jaxrl2_finetuning_benchmark/experiment_output/jaxrl/0603_cql_widowx_debug_cql_alpha_5_dataset_debug_seed_0_2023_06_03_11_36_09_0000--s-0
override_critic_lr:
  desc: null
  value: -1.0
policy_encoder_type:
  desc: null
  value: small
posneg_schedule_interval:
  desc: null
  value: -1.0
posneg_schedule_ratio:
  desc: null
  value: 1.0
prefix:
  desc: null
  value: 0603_cql_widowx_debug_cql_alpha_5_dataset_debug_seed_0
pretrained_encoder:
  desc: null
  value: null
rescale_critic_last_layer_ratio:
  desc: null
  value: -1
reset_critic:
  desc: null
  value: null
restore_path:
  desc: null
  value: ''
rew_func_for_target_only:
  desc: null
  value: 0
reward_func_type:
  desc: null
  value: 0
reward_scale:
  desc: null
  value: 11.0
reward_shift:
  desc: null
  value: -1
reward_type:
  desc: null
  value: final_one
save_replay_buffer:
  desc: null
  value: false
save_video:
  desc: null
  value: false
seed:
  desc: null
  value: 0
share_encoders:
  desc: null
  value: 0
softmax_temperature:
  desc: null
  value: -1
start_online_updates:
  desc: null
  value: 1000
stochastic_data_collect:
  desc: null
  value: 1
stochastic_evals:
  desc: null
  value: false
suffix:
  desc: null
  value: ''
target_entropy:
  desc: null
  value: null
target_mixing_ratio:
  desc: null
  value: 0.9
tau:
  desc: null
  value: 0.005
temp_lr:
  desc: null
  value: 0.0003
tpu_port:
  desc: null
  value: 8820
tqdm:
  desc: null
  value: 1
tr_penalty_coefficient:
  desc: null
  value: 0.0
train_kwargs:
  desc: null
  value:
    actor_lr: 0.0001
    adam_weight_decay: -1.0
    backup_entropy: 0
    bound_q_with_mc: false
    cnn_features:
    - 32
    - 32
    - 32
    - 32
    cnn_padding: VALID
    cnn_strides:
    - 2
    - 1
    - 1
    - 1
    cql_alpha: 5.0
    critic_lr: 0.0003
    critic_reduction: min
    cross_norm: false
    decay_steps: null
    discount: 0.96
    dr3_coefficient: 0.0
    dropout_rate: null
    encoder_norm: batch
    encoder_resize_dim: 128
    encoder_type: small
    freeze_encoders_actor: false
    freeze_encoders_critic: false
    hidden_dims:
    - 256
    - 256
    init_temperature: 1.0
    latent_dim: 50
    max_q_backup: 1
    mc_penalty_coefficient: 0.0
    method: 0
    method_const: 0.0
    method_type: 0
    online_bound_nstep_return: -1
    policy_encoder_type: small
    share_encoders: 0
    softmax_temperature: -1
    target_entropy: null
    tau: 0.005
    temp_lr: 0.0003
    tr_penalty_coefficient: 0.0
    use_spatial_softmax: 1
    wait_actor_update: 9999999999999
trajwise_alternating:
  desc: null
  value: 1
use_negatives:
  desc: null
  value: false
use_spatial_softmax:
  desc: null
  value: 1
use_terminals:
  desc: null
  value: 1
utd_schedule_interval:
  desc: null
  value: -1.0
utd_schedule_ratio:
  desc: null
  value: 1.0
wait_actor_update:
  desc: null
  value: -1
wandb_project:
  desc: null
  value: 0603_cql_widowx
